### PR TITLE
Makework commit for a PR to try bot rerendering. [ci skip] [skip ci]

### PR DESCRIPTION
**Pull request by pkgw**
Testing rerendering in for the `build_artifacts` problem.

### CODE REVIEW

**Comment by pkgw** [comment]
@conda-forge-admin, please rerender

**Comment by pkgw** [comment]
@conda-forge/core I've rerendered this recipe with the new conda-smithy and it seems to mostly work, but the very last stage of the Linux build breaks because the build artifacts are landing in `/opt/conda/conda-bld` rather than `/home/conda/feedstock_root`. Any idea why that might be happening?

**Comment by ocefpaf** [comment]
See https://github.com/conda-forge/conda-smithy/issues/762

BTW, the failure happens after the upload, so if you don't mind the failing status it would be OK to merge this :smile:

**Comment by pkgw** [comment]
[One step ahead of you](https://github.com/conda-forge/aipy-feedstock/pull/10#issuecomment-385863163). I guess I'll leave this PR open to have an easy way to rerender (if needed) when this gets fixed.

**Comment by ocefpaf** [comment]
[This one](https://github.com/conda-forge/pandas-feedstock/pull/42) was re-rendered with the `master` version of conda-smithy, it seems OK. I'll try to issue a new release as soon as possible.

**Comment by isuruf** [comment]
@ocefpaf, doesn't work

**Comment by ocefpaf** [comment]
> @ocefpaf, doesn't work

Not sure what is not working but I haven't looked at the logs yet... The status is green though.

**Comment by pkgw** [comment]
@ocefpaf It might depend on the definition of "works"? The script manually creates `build_artifacts` so the `touch` command works, but the build root is still in `/opt/conda`.

**Comment by pkgw** [comment]
@conda-forge-admin, please rerender

**Pull request merged**
